# Generated by Django 4.1.7 on 2023-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
